// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace JWTUAuthLogin.DBModel;

public partial class MBDatabaseContext : DbContext
{
    public MBDatabaseContext(DbContextOptions<MBDatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SysErrorLog> SysErrorLogs { get; set; }

    public virtual DbSet<UserDatum> UserData { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SysErrorLog>(entity =>
        {
            entity.HasKey(e => e.ErrorLogId).HasName("PK__SysError__D65247C23ABF6420");

            entity.ToTable("SysErrorLog");

            entity.Property(e => e.ErrorLogId).HasMaxLength(50);
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.LogOn).HasColumnType("datetime");
            entity.Property(e => e.Priority)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Program)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<UserDatum>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__UserData__1788CC4C3DD9B2A1");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.DeviceID).HasMaxLength(50);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.LocalTimeZone).HasMaxLength(50);
            entity.Property(e => e.Manufacturer).HasMaxLength(100);
            entity.Property(e => e.ModelNo).HasMaxLength(50);
            entity.Property(e => e.NewPassword).HasMaxLength(50);
            entity.Property(e => e.OS)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.OSVersion).HasMaxLength(50);
            entity.Property(e => e.OldPassword).HasMaxLength(50);
            entity.Property(e => e.Password).HasMaxLength(100);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}