// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JWTUAuthLogin.DBModel;

public partial class SysAttachment
{
    public string AttachId { get; set; }

    public DateTime? AttachOn { get; set; }

    public string AttachFileName { get; set; }

    public string AttachFilePath { get; set; }

    public string AttachUrl { get; set; }

    public string OriginalFileName { get; set; }

    public string ReferenceId { get; set; }

    public string ReferenceType { get; set; }

    public decimal? FileSize { get; set; }

    public string Sector { get; set; }

    public string Remark { get; set; }

    public bool? Active { get; set; }

    public string CraatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string LastAction { get; set; }

    public bool? IsMobileAtt { get; set; }

    public string LicenseId { get; set; }
}