// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JWTUAuthLogin.DBModel;

public partial class SysErrorLog
{
    public string ErrorLogId { get; set; }

    public DateTime LogOn { get; set; }

    public string Program { get; set; }

    public string Description { get; set; }

    public string Priority { get; set; }

    public string UserId { get; set; }

    public string UserCode { get; set; }
}