// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JWTUAuthLogin.DBModel;

public partial class UserDatum
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string EmailConfirmation { get; set; }

    public string OS { get; set; }

    public string OSVersion { get; set; }

    public string ModelNo { get; set; }

    public string Manufacturer { get; set; }

    public string RegToken { get; set; }

    public string LocalTimeZone { get; set; }

    public string DeviceID { get; set; }

    public string OldPassword { get; set; }

    public string NewPassword { get; set; }
}